### ISSUE TITLE
Update README to clarify your project idea

### ISSUE THREAD

**Issue by ltdangkhoa** [ngthgph/namer-app#1]
Hi,

Could you add some details about your project on README.md?

**Comment by ngthgph** [comment]
Hi Kris,

Project content and its features have been added. Please help to review.

**Comment by ltdangkhoa** [comment]
Thanks for your updated.

Could you please add more info on how to make this project run? 
For example, if a user clone your project to Windows environment, how can he/she make the app run?

Here is my suggestions on MacOS environment:

---

## How to run on Mac/Unix:

### Install Flutter SDK
Following instructions on flutter.dev to setup environment... 

### Running from CLI:

```
$ cd ../project_root
$ flutter clean
$ flutter pub get
$ flutter run
```

Depend on devices you would like to make run on, select device number to continue
```
Connected devices:
macOS (desktop) • macos  • darwin-x64     • macOS 14.2.1 23C71 darwin-x64
Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.62

Wirelessly connected devices:

[1]: macOS (macos)
[2]: Chrome (chrome)
```
...

**Comment by ngthgph** [comment]
The guide has been added to README. Please help to check again.

**Comment by ltdangkhoa** [comment]
LGTM
