### ISSUE TITLE
Add feature to save favorite words after reload app

### ISSUE THREAD

**Issue by ltdangkhoa** [ngthgph/namer-app#3]
As users interested on words style will be varies, it would be an option for them to choose which style will be used (lowerCase, PascalCase, camel_case...)

Wish to see these new features on your app:
- [x] Option to choose words format style
- [x] The option as well as the favorite words can be saved for later session (use shared_preferences package ^.^)

**Comment by ngthgph** [comment]
Two new features have been added. If possible, could you please leave your feedback for improving the code?
Thank you.

**Comment by ltdangkhoa** [comment]
LGTM
